[project]
name = "opennutria"
version = "0.1.0"
description = "An open-source app for precise food and meal analysis"
authors = [
    {name = "Andre Lanrezac",email = "a.lanrezac@gmail.com"}
]
license = {text = "Apache License 2.0"}
readme = "README.md"
requires-python = "^3.13"
dependencies = [
    "django (>=5.2.1,<6.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
